server {
    listen       80;
    listen       [::]:80;
    server_name  localhost;
    gzip_static on;

    include /etc/nginx/csp_nginx.conf;
    include /etc/nginx/branch_location_nginx.conf;

    location / {
        if ($uri = '/index.html') {
          add_header Cache-Control "no-cache, no-store, must-revalidate";
          add_header Pragma "no-cache";
        }

        root   /usr/share/nginx/html;
        index  index.html index.htm;
	      try_files $uri $uri/ /index.html;
    }

    location /ping {
        root   /usr/share/nginx/html;
        index  ping.json;
	      try_files $uri $uri/ /ping.json;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
